language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t eguziy/fibonacci-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true eguziy/fibonacci-test npm run test -- --coverage

after_success:
  - docker build -t eguziy/fibonacci-client -f ./client/Dockerfile ./client
  - docker build -t eguziy/fibonacci-nginx -f ./nginx/Dockerfile ./nginx
  - docker build -t eguziy/fibonacci-server -f ./server/Dockerfile ./server
  - docker build -t eguziy/fibonacci-worker -f ./worker/Dockerfile ./worker