version: "3"
services:
  api:
    image: eguziy/fibonacci-server
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: eguziy/fibonacci-worker
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
  client:
    restart: always
    mem_limit: 128m
    hostname: client
    image: eguziy/fibonacci-client
  nginx:
    restart: always
    mem_limit: 128m
    hostname: nginx
    image: eguziy/fibonacci-nginx
    ports:
      - "80:80"