name: "Fibonacci ci"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker build -t eguziy/fibonacci-test -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true eguziy/fibonacci-test npm run test -- --coverage
  build-and-deploy-images:
    needs: run-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u="${{secrets.DOCKER_ID}}" -p="${{secrets.DOCKER_PASSWORD}}"
      - run: |
          docker build -t eguziy/fibonacci-client -f ./client/Dockerfile ./client
          docker push "${{secrets.DOCKER_ID}}/fibonacci-client"
      - run: |
          docker build -t eguziy/fibonacci-nginx -f ./nginx/Dockerfile ./nginx
          docker push "${{secrets.DOCKER_ID}}/fibonacci-nginx"
      - run: |
          docker build -t eguziy/fibonacci-server -f ./server/Dockerfile ./server
          docker push "${{secrets.DOCKER_ID}}/fibonacci-server"
      - run: |
          docker build -t eguziy/fibonacci-worker -f ./worker/Dockerfile ./worker
          docker push "${{secrets.DOCKER_ID}}/fibonacci-worker"
  deploy-app-to-amazon-bean-stalk:
    needs: [run-test, build-and-deploy-images]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: fibonacci
          environment_name: Fibonacci-env
          existing_bucket_name: elasticbeanstalk-ap-northeast-1-775678912010
          version_label: ${{ github.sha }}
          region: ap-northeast-1
          deployment_package: deploy.zip

  
