name: "Fibonacci ci"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-test:
    run-on: ubuntu-latest
    steps:
      - run: docker build -t eguziy/fibonacci-test -f ./client/Dockerfile.dev ./client
      - run: docker run eguziy/fibonacci-test npm run test -- --coverage
  build-images:
    needs: run-test
    run-on: ubuntu-latest
    steps:
      - run: docker build -t eguziy/fibonacci-client -f ./client/Dockerfile ./client
      - run: docker build -t eguziy/fibonacci-nginx -f ./nginx/Dockerfile ./nginx
      - run: docker build -t eguziy/fibonacci-server -f ./server/Dockerfile ./server
      - run: docker build -t eguziy/fibonacci-worker -f ./worker/Dockerfile ./worker
  
  
